increased version number to 3.0
Ofisare/VRCompanion pull request #6
Opened 2024-07-07 15:16 UTC by drowhunter

changed vr global name from openVR to vr

2024-07-07 15:19 UTC, drowhunter commented
line 438  of vr_companion.py  not sure where this function is 

`FreePIE_version_2_0_required()`

but maybe it should be renamed to something like 

`Validate_Freepie_Version()`

2024-07-07 18:04 UTC, Ofisare commented
> line 438 of vr_companion.py not sure where this function is
> 
> `FreePIE_version_2_0_required()`
> 
> but maybe it should be renamed to something like
> 
> `Validate_Freepie_Version()`

It does not exists, thus it throws an error and stops the script with a "more readable" message :D

2024-07-09 08:15 UTC, Ofisare requested changes

2024-07-09 08:15 UTC, Ofisare commented on README.md
> + - download the [complete build with script and profiles](https://github.com/Ofisare/VRCompanion/releases/latest)
Latest is not good, latest might only contain the scripts. This is always a reference to the "latest" complete build with freepie.

2024-07-09 08:15 UTC, Ofisare commented on scripts/vr_companion.py
> +    requiredVersion = "3.0"
Here, I would then also remain at 2.0

2024-07-09 08:15 UTC, Ofisare commented on scripts/README.md
> +Under `Settings > Plugins > Open VR` you can switch the vr Runtime to be used:
here we missed one open

2024-07-09 08:18 UTC, Ofisare approved these changes

2024-07-09 08:18 UTC, merged